apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deployment"
  namespace: $K8S_NAMESPACE
spec:
  selector:
    matchLabels:
      app: $K8S_NAMESPACE
  replicas: 2
  template:
    metadata:
      labels:
        app: $K8S_NAMESPACE
    spec:
      containers:
      - image: $ECR_REPOSITORY_URL:$IMAGE_TAG
        imagePullPolicy: Always
        name: $K8S_NAMESPACE
        ports:
        - containerPort: 8080
