apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  namespace: $K8S_NAMESPACE
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: $K8S_NAMESPACE
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service"
              servicePort: 80
