apiVersion: v1
kind: Service
metadata:
  name: "service"
  namespace: $K8S_NAMESPACE
  annotation:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: "http"
      targetPort: 8080
      protocol: TCP
    - port: 443
      name: "https"
      targetPort: 8080
      protocol: TCP
  selector:
    app: $K8S_NAMESPACE
