 apiVersion: v1
kind: Service
metadata:
  name: "backend"
  namespace: $K8S_NAMESPACE
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "backend"