name: 'Dev WorkFlow'
on:
  push:
    branches:
      - dev
      - ft-ci-pipeline-10 #TODO: remove
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        terraform_version: 0.12.28

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.28

    - name: Terraform Init
      run: terraform init

    - name: Terraform Setup Workspace
      run: terraform workspace new dev

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="../../infra/values/dev.tfvars"

    - name: Terraform Apply
      run: terraform apply -var-file="../../infra/values/dev.tfvars" -auto-approve
